name: "test_action_outputs"
on:
  push:
    branches:
      - "main"
jobs:
  env-variables:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Set variables"
        id: "set-vars"
        run: |
          echo ${{ github.event }}
          echo ${{ github.head_commit.message }}
          echo $(echo "$GITHUB_REF" | awk -F / '{print $3}')